### ISSUE TITLE
March Equinox != 春分

### ISSUE THREAD

**Issue by liyishuai** [liweitianux/ccalendar#3]
```shell
calendar -s chinese
```
> 春分 (Chūnfēn    ):   0°, 2020-03-20 11:49:33 +08:00

```shell
calendar -s sun -U +08:00
```
> March Equinox    :   0°, 2020-03-20 11:49:32

Where does this 1-second difference come from?

**Comment by liweitianux** [comment]
Yeah. I also noticed this minor mismatch. This time I had a closer look and the direct reason is the approximation date passed to the `solar_longitude_atafter()` function:

* for the **chinese** case, it's the date of the last Jieqi, i.e., 2020-03-06; see https://github.com/liweitianux/ccalendar/blob/master/src/chinese.c#L563
* for the **sun** case, it's the first day of that month, i.e., 2020-03-01; see https://github.com/liweitianux/ccalendar/blob/master/src/sun.c#L406

Actually, if i change the `date.day = 1` to `date.day = 6` in `sun.c`, I can get the same time of the Chunfen Jieqi and March Equinox.

In principle, the `solar_longitude_onafter()` should give a precision of about 0.1 second, so there should not be such a mismatch.  Need to investigate this issue further.

Cheers

**Comment by liweitianux** [comment]
Sorry for the long delay.

Well, I've had a further look into this issue and figured it out that it's not an error.

The precision of `solar_longitude_onafter()` calculation is indeed about 0.1 second (see `eps = 1e-6` in `invert_angular()` in `utils.c`).  But the output time is round to be second-precision, so there can be 1-second difference.

By adding some debug prints I get `t1 =  737504.492736872751266` for March Equinox (2020-03-20 11:49:32 +08:00) and `t2 = 737504.492737355991267` for 春分 (2020-03-20 11:49:33 +08:00).  So:

```
(t1 - t2) * 10^6 = -0.483240001000000
(t1 - floor(t1)) * 86400 = 42572.465805709382400 --> 42572
(t2 - floor(t2)) * 86400 = 42572.507557645468800 --> 42573
```

Given the astronomical algorithms used in this tool have a precision about several seconds, so it's meaningless to show time with sub-second precision.  And I've mentioned in the `calendar(1)` man page that the accuracy of events is about several minutes.  This tool is not a serious astronomical calculator ;)

cheers
